# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Senf CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - '**'

jobs:
  custom-cypress-run:
    env:
      REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
      REACT_APP_DB_BASE_URL: https://europe-west1-senf-dev.cloudfunctions.net/api
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress
        run: npm run cypress:ci
